# Javascript Node CircleCI 2.0 configuration file
# 
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# We need to 
<<<<<<< HEAD
# - build, test, deploy server for staging and production
# - build, test, deploy client for staging and production

=======
# - build, test, deploy for staging and production
>>>>>>> b8eaa57f9ae007fddb6c21b8cc0bd213db7af253
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      # - image: circleci/mongo:3.4.4
    working_directory: ~/deployment-staging/front
    steps:
      - run: yarn install

  test:
   docker:
     -image: circleci/node:8.9.4
    steps:
      - run: yarn test

workflows:
 version: 2
 build_and_test:
  jobs:
	- build
	-test :
	  	requires:
		 - build
	
	
